"""Gradio interface for Text Processing App.

Location: khadijaedarzi9/gradio_app/app.py
This file contains only UI code and imports functions from operations.py
"""

import datetime
from typing import Tuple

import gradio as gr
from operations import (
    FileExporter,
    analyze_text,
    convert_text,
    correct_text,
    generate_word_cloud,
    reverse_text,
    save_as_pdf,
    save_as_txt,
)


class TextStyler:
    """Apply styling to text based on font, size, and type."""

    FONT_FAMILIES = {
        "Arial": "Arial, sans-serif",
        "Times New Roman": "'Times New Roman', serif",
        "Courier": "'Courier New', monospace",
    }

    @staticmethod
    def apply_style(text: str, font: str, size: str, text_type: str) -> str:
        """Apply HTML styling to text."""
        if not text:
            return ""

        font_family = TextStyler.FONT_FAMILIES.get(font, "Arial, sans-serif")
        font_size = f"{size}px"

        if text_type == "Title":
            weight = "bold"
            transform = "uppercase"
        elif text_type == "Subtitle":
            weight = "600"
            transform = "capitalize"
        else:
            weight = "normal"
            transform = "none"

        style = (
            f"font-family: {font_family}; font-size: {font_size}; font-weight: {weight}; text-transform: {transform};"
        )

        return f'<div style="{style}">{text}</div>'


def get_empty_html() -> str:
    """Return empty HTML placeholder."""
    return (
        "<div style='padding: 15px; min-height: 300px; "
        "border: 1px solid #ddd; border-radius: 8px; "
        "background-color: #f8f9fa;'>"
        "<p style='text-align: center; color: #666;'>"
        "Your corrected and styled text will appear "
        "here as you type</p></div>"
    )


def handle_live_correction(text: str, font: str, size: str, text_type_val: str) -> Tuple[str, str]:
    """Correct text and apply styling in real-time."""
    if not text or not text.strip():
        return get_empty_html(), ""

    corrected_text = correct_text(text)
    styled = TextStyler.apply_style(corrected_text, font, size, text_type_val)
    styled_html = (
        f"<div style='padding: 15px; min-height: 300px; "
        f"border: 1px solid #ddd; border-radius: 8px; "
        f"background-color: #f8f9fa;'>{styled}</div>"
    )
    return styled_html, corrected_text


def handle_conversion(corrected_text: str, mode: str) -> str:
    """Handle text conversion."""
    if not corrected_text:
        return "Please correct text in the Correction tab first."
    return convert_text(corrected_text, mode)


def handle_reversal(corrected_text: str, mode: str) -> str:
    """Handle text reversal."""
    if not corrected_text:
        return "Please correct text in the Correction tab first."
    return reverse_text(corrected_text, mode)


def handle_analysis(corrected_text: str) -> Tuple[str, str]:
    """Handle text analysis and word cloud generation."""
    if not corrected_text:
        no_text_msg = "Please correct text in the Correction tab first."
        no_text_html = "<p style='text-align: center; color: #666;'>No text to analyze</p>"
        return no_text_msg, no_text_html

    analysis = analyze_text(corrected_text)
    wc = generate_word_cloud(corrected_text)

    ana_str = (
        f"Total Words: {analysis['word_count']}\n\n"
        f"Total Characters: {analysis['char_count']}\n\n"
        f"Sentences: {analysis['sentence_count']}\n\n"
        f"Average Word Length: "
        f"{analysis['avg_word_length']} characters\n\n"
        f"Most Frequent Word: '{analysis['most_common']}'"
    )

    return ana_str, wc


def create_aggregated_content(corrected_text: str, conv_text: str, rev_text: str, analysis_text: str, fmt: str) -> str:
    """Create aggregated content for export."""
    corrected_val = corrected_text or ""
    converted_val = conv_text or "Not converted yet"
    reversed_val = rev_text or "Not reversed yet"
    analysis_val = analysis_text or "Not analyzed yet"

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return (
        f"{'=' * 70}\n"
        f"{'SMART TEXT STUDIO - COMPLETE EXPORT':^70}\n"
        f"{'=' * 70}\n\n"
        f"Export Date: {timestamp}\n"
        f"Format: {fmt.upper()}\n"
        f"{'=' * 70}\n\n\n"
        f"{'CORRECTED TEXT':^70}\n"
        f"{'-' * 70}\n\n{corrected_val}\n\n\n"
        f"{'=' * 70}\n\n\n"
        f"{'CONVERTED TEXT':^70}\n"
        f"{'-' * 70}\n\n{converted_val}\n\n\n"
        f"{'=' * 70}\n\n\n"
        f"{'REVERSED TEXT':^70}\n"
        f"{'-' * 70}\n\n{reversed_val}\n\n\n"
        f"{'=' * 70}\n\n\n"
        f"{'TEXT ANALYSIS':^70}\n"
        f"{'-' * 70}\n\n{analysis_val}\n\n\n"
        f"{'=' * 70}\n"
        f"End of document - Generated by Smart Text Studio\n"
        f"{'=' * 70}\n"
    )


def handle_download(
    corrected_text: str, conv_text: str, rev_text: str, analysis_text: str, format_selected: str
) -> str:
    """Handle file download."""
    fmt = "pdf" if "PDF" in format_selected else "txt"

    if not corrected_text:
        error_path = FileExporter._get_filename(fmt)
        error_msg = "ERROR: No content to export.\nPlease correct text first in the Correction tab."

        if fmt == "txt":
            with open(error_path, "w", encoding="utf-8") as f:
                f.write(error_msg)
        else:
            from fpdf import FPDF

            pdf = FPDF()
            pdf.add_page()
            pdf.set_font("Arial", size=12)
            pdf.multi_cell(0, 10, txt=error_msg)
            pdf.output(error_path)

        return error_path

    aggregated = create_aggregated_content(corrected_text, conv_text, rev_text, analysis_text, fmt)

    try:
        if fmt == "txt":
            return save_as_txt(aggregated)
        elif fmt == "pdf":
            return save_as_pdf(aggregated)
        else:
            return save_as_txt(aggregated)
    except Exception as e:
        error_path = FileExporter._get_filename(fmt)
        error_msg = f"ERROR: Export failed\nDetails: {str(e)}"

        if fmt == "txt":
            with open(error_path, "w", encoding="utf-8") as f:
                f.write(error_msg)
        else:
            from fpdf import FPDF

            pdf = FPDF()
            pdf.add_page()
            pdf.set_font("Arial", size=12)
            pdf.multi_cell(0, 10, txt=error_msg)
            pdf.output(error_path)

        return error_path


def build_correction_tab(corrected_plain: gr.Textbox) -> None:
    """Build the correction tab."""
    with gr.Row():
        font_dropdown = gr.Dropdown(
            label="Font",
            choices=["Arial", "Times New Roman", "Courier"],
            value="Arial",
            interactive=True,
        )
        size_dropdown = gr.Dropdown(
            label="Character size",
            choices=["10", "12", "14", "16", "18"],
            value="12",
            interactive=True,
        )
        text_type = gr.Dropdown(
            label="Text type",
            choices=["Title", "Subtitle", "Body"],
            value="Body",
            interactive=True,
        )

    with gr.Row():
        with gr.Column():
            input_text = gr.Textbox(
                label="Enter your text below",
                lines=10,
                placeholder="Start typing... text will be corrected and styled automatically",
            )
            reset_btn = gr.Button("Reset", size="lg")

        with gr.Column():
            corrected = gr.HTML(value=get_empty_html(), label="Corrected & Styled Text (Live Preview)")

    input_text.change(
        handle_live_correction,
        inputs=[input_text, font_dropdown, size_dropdown, text_type],
        outputs=[corrected, corrected_plain],
    )

    for dropdown in [font_dropdown, size_dropdown, text_type]:
        dropdown.change(
            handle_live_correction,
            inputs=[input_text, font_dropdown, size_dropdown, text_type],
            outputs=[corrected, corrected_plain],
        )

    def reset_fields() -> Tuple[str, str, str]:
        return "", get_empty_html(), ""

    reset_btn.click(reset_fields, inputs=None, outputs=[input_text, corrected, corrected_plain])


def build_converter_tab(corrected_plain: gr.Textbox) -> gr.Textbox:
    """Build the converter tab."""
    with gr.Row():
        with gr.Column():
            conv_choice = gr.Dropdown(
                label="Conversion Type",
                choices=["Uppercase", "Lowercase", "Title Case"],
                value="Uppercase",
            )
            conv_btn = gr.Button("Convert", variant="primary", size="lg")
        with gr.Column():
            conv_output = gr.Textbox(label="Converted text", lines=10)

    conv_btn.click(handle_conversion, inputs=[corrected_plain, conv_choice], outputs=conv_output)

    return conv_output


def build_reverser_tab(corrected_plain: gr.Textbox) -> gr.Textbox:
    """Build the reverser tab."""
    with gr.Row():
        with gr.Column():
            rev_choice = gr.Radio(
                label="Reverse Type",
                choices=["words", "characters"],
                value="words",
                info="Choose how to reverse the text",
            )
            rev_btn = gr.Button("Reverse", variant="primary", size="lg")
        with gr.Column():
            rev_output = gr.Textbox(label="Reversed text", lines=10)

    rev_btn.click(handle_reversal, inputs=[corrected_plain, rev_choice], outputs=rev_output)

    return rev_output


def build_analyzer_tab(corrected_plain: gr.Textbox) -> gr.Textbox:
    """Build the analyzer tab."""
    with gr.Row():
        with gr.Column():
            ana_btn = gr.Button("Analyze Text", variant="primary", size="lg")
        with gr.Column():
            ana_output = gr.Textbox(label="Analysis Results", lines=8, interactive=False)

    gr.Markdown("### Word Cloud Visualization")
    wc_output = gr.HTML(
        value="<p style='text-align: center; color: #666;'>Click 'Analyze Text' to generate word cloud</p>",
        elem_classes="word-cloud-html",
    )

    ana_btn.click(
        handle_analysis,
        inputs=corrected_plain,
        outputs=[ana_output, wc_output],
    )

    return ana_output


def build_download_tab(
    corrected_plain: gr.Textbox, conv_output: gr.Textbox, rev_output: gr.Textbox, ana_output: gr.Textbox
) -> None:
    """Build the download tab."""
    gr.Markdown("### Export all your processed text")

    with gr.Row():
        with gr.Column(scale=2):
            format_choice = gr.Radio(
                label="Choose your export format:", choices=["TXT", "PDF"], value="TXT", interactive=True
            )
        with gr.Column(scale=1):
            download_btn = gr.Button("Download", variant="primary", size="lg")

    download_file = gr.File(label="", visible=True, interactive=False)

    download_btn.click(
        handle_download,
        inputs=[corrected_plain, conv_output, rev_output, ana_output, format_choice],
        outputs=download_file,
    )


def build_interface() -> gr.Blocks:
    """Construct and return the Gradio Blocks interface."""
    theme = gr.themes.Soft(
        primary_hue="indigo",
        neutral_hue="slate",
        font=["Inter", "sans-serif"],
        radius_size="lg",
    )

    css = """
    .word-cloud-html { min-height: 200px; }
    .styled-text { padding: 15px; border-radius: 8px;
                   background-color: #f8f9fa; }
    """

    with gr.Blocks(theme=theme, css=css) as interface:
        gr.Markdown("# Text Processing App")
        gr.Markdown("Refine, convert, analyze and export your text.")

        corrected_plain = gr.Textbox(visible=False, value="")

        with gr.Tabs():
            with gr.Tab("Correction"):
                build_correction_tab(corrected_plain)

            with gr.Tab("Converter"):
                conv_output = build_converter_tab(corrected_plain)

            with gr.Tab("Reverser"):
                rev_output = build_reverser_tab(corrected_plain)

            with gr.Tab("Analyzer & Word Cloud"):
                ana_output = build_analyzer_tab(corrected_plain)

            with gr.Tab("Download"):
                build_download_tab(corrected_plain, conv_output, rev_output, ana_output)

    return interface


def main() -> None:
    """Main function to launch the application."""
    demo = build_interface()
    demo.launch()


if __name__ == "__main__":
    main()
