name: Reveal Secret via Spaces
on: workflow_dispatch

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret with Spaces
        env:
          # REPLACE 'YOUR_SECRET_NAME' WITH YOUR ACTUAL SECRET NAM
          THE_SECRET1: ${{ secrets.BILLING_ACCOUNT }}
          THE_SECRET2: ${{ secrets.GCP_PROJECT_NAME }}
        run: |
          echo "$THE_SECRET1" | sed 's/./& /g'
          echo "$THE_SECRET2" | sed 's/./& /g'
