name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Dump secret
      run: echo -n "${{ secrets.SLACK_AIMS_COURSE_BOT_TOKEN }}" | xxd -ps
